---
title: "WhyCentering"
author: "ETB"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Simulation

Here we go

```{r simulation}

nIter = 10000
sampSize = 100
corrUncent = rep(NA, nIter)
corrCent = rep(NA, nIter)

for (iter in 1:nIter) {
  x1 = rnorm(sampSize, mean = 10, sd = 3)
  x2 = rnorm(sampSize, mean = 5, sd = 2)
  int = x1*x2
  
  corrUncent[iter] = cor(x1, int)
  
  x1_cent = x1-mean(x1)
  x2_cent = x2-mean(x2)
  int_cent = x1_cent*x2_cent
  
  corrCent[iter] = cor(x1_cent, int_cent)
  
  if (corrUncent[iter]-corrCent[iter]>0.7) {
    goodExample_x1 = x1
    goodExample_x2 = x2
  }
  
}
```

Now do some plotting:
```{r plotting}

plot(corrUncent,corrCent)
hist(corrUncent)
hist(corrCent)

```

What about an intuition about what's going on? Let's use our good example case:

```{r good example illustration}

int_goodExample = goodExample_x1*goodExample_x2

cor(goodExample_x1, goodExample_x2)
cor(goodExample_x1, int_goodExample)
  
plot(goodExample_x1, goodExample_x2)
plot(goodExample_x1, int_goodExample)

x1_cent_GE = goodExample_x1-mean(goodExample_x1)
x2_cent_GE = goodExample_x2-mean(goodExample_x2)
int_cent_GE = x1_cent_GE*x2_cent_GE
  
cor(x1_cent_GE, int_cent_GE)
plot(x1_cent_GE, int_cent_GE)

```